# Generated by Django 5.2.4 on 2026-03-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('hero_bg', 'Home — Hero Background'), ('about_image', 'Home — About Section Image'), ('photo_strip_1', 'Home — Photo Strip 1 (left)'), ('photo_strip_2', 'Home — Photo Strip 2 (center)'), ('photo_strip_3', 'Home — Photo Strip 3 (right)')], max_length=30, unique=True)),
                ('file', models.FileField(upload_to='site_media/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Media',
                'verbose_name_plural': 'Site Media',
            },
        ),
    ]
