# Generated by Django 5.2.4 on 2026-03-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b3rc_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemedia',
            name='slot',
            field=models.CharField(choices=[('hero_bg', 'Home — Hero Background'), ('about_image', 'Home — About Section Image'), ('photo_strip_1', 'Home — Photo Strip 1 (left)'), ('photo_strip_2', 'Home — Photo Strip 2 (center)'), ('photo_strip_3', 'Home — Photo Strip 3 (right)'), ('tagline_bg', 'Home — Tagline Background')], max_length=30, unique=True),
        ),
    ]
