# Generated by Django 5.2.4 on 2026-03-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b3rc_site', '0002_alter_sitemedia_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Carousel Image',
                'verbose_name_plural': 'Carousel Images',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='sitemedia',
            name='slot',
            field=models.CharField(choices=[('hero_bg', 'Home — Hero Background'), ('about_image', 'Home — About Section Image'), ('tagline_bg', 'Home — Tagline Background')], max_length=30, unique=True),
        ),
    ]
