# Generated by Django 5.2.4 on 2026-03-28 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b3rc_site', '0004_product_order_orderitem_productimage_productvariant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('category', models.CharField(choices=[('EVENT', 'Club Event'), ('PARKRUN', 'Parkrun'), ('RACE', 'Race Recap'), ('TRAINING', 'Training Report'), ('NEWS', 'Club News')], default='EVENT', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('body', models.TextField(help_text='Markdown supported')),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL')),
                ('event_date', models.DateField(blank=True, help_text='Date the event took place', null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('strava_url', models.URLField(blank=True, help_text='Link to Strava activity or club event')),
                ('is_featured', models.BooleanField(default=False, help_text='Pin to top of blog list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
