# Generated by Django 5.2.4 on 2026-03-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b3rc_site', '0006_postcomment_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('link_url', models.CharField(blank=True, help_text='Internal path (e.g. /en/blog/slug/) or full external URL', max_length=500)),
                ('link_label', models.CharField(blank=True, default='Read more', max_length=100)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('bg_color', models.CharField(default='#0B3C56', help_text='Hex colour, e.g. #0B3C56', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-valid_from'],
            },
        ),
    ]
